// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_ddx_mc
arma::mat get_ddx_mc(const arma::vec& beta, const arma::mat& vcov, const arma::mat& x, const arma::mat& xp, const arma::umat& wei_locs, const arma::vec& wei_vals, const Rcpp::NumericVector& probs, const unsigned int& link, const unsigned int& iter);
RcppExport SEXP _DAME_get_ddx_mc(SEXP betaSEXP, SEXP vcovSEXP, SEXP xSEXP, SEXP xpSEXP, SEXP wei_locsSEXP, SEXP wei_valsSEXP, SEXP probsSEXP, SEXP linkSEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vcov(vcovSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type wei_locs(wei_locsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wei_vals(wei_valsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type iter(iterSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ddx_mc(beta, vcov, x, xp, wei_locs, wei_vals, probs, link, iter));
    return rcpp_result_gen;
END_RCPP
}
// get_dydx_mc
arma::mat get_dydx_mc(const arma::vec& beta, const arma::mat& vcov, const arma::mat& x, const arma::mat& d2mdxdb, const arma::umat& wei_locs, const arma::vec& wei_vals, const Rcpp::NumericVector& probs, const unsigned int& link, const unsigned int& iter);
RcppExport SEXP _DAME_get_dydx_mc(SEXP betaSEXP, SEXP vcovSEXP, SEXP xSEXP, SEXP d2mdxdbSEXP, SEXP wei_locsSEXP, SEXP wei_valsSEXP, SEXP probsSEXP, SEXP linkSEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vcov(vcovSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type d2mdxdb(d2mdxdbSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type wei_locs(wei_locsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wei_vals(wei_valsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type link(linkSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type iter(iterSEXP);
    rcpp_result_gen = Rcpp::wrap(get_dydx_mc(beta, vcov, x, d2mdxdb, wei_locs, wei_vals, probs, link, iter));
    return rcpp_result_gen;
END_RCPP
}
// get_ddx_delta
arma::mat get_ddx_delta(const arma::vec& beta, const arma::mat& vcov, const arma::mat& x, const arma::mat& xp, const arma::umat& wei_locs, const arma::vec& wei_vals, const Rcpp::NumericVector& probs, const unsigned int& link);
RcppExport SEXP _DAME_get_ddx_delta(SEXP betaSEXP, SEXP vcovSEXP, SEXP xSEXP, SEXP xpSEXP, SEXP wei_locsSEXP, SEXP wei_valsSEXP, SEXP probsSEXP, SEXP linkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vcov(vcovSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type wei_locs(wei_locsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wei_vals(wei_valsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type link(linkSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ddx_delta(beta, vcov, x, xp, wei_locs, wei_vals, probs, link));
    return rcpp_result_gen;
END_RCPP
}
// get_dydx_delta
arma::mat get_dydx_delta(const arma::vec& beta, const arma::mat& vcov, const arma::mat& x, const arma::mat& d2mdxdb, const arma::umat& wei_locs, const arma::vec& wei_vals, const Rcpp::NumericVector& probs, const unsigned int& link);
RcppExport SEXP _DAME_get_dydx_delta(SEXP betaSEXP, SEXP vcovSEXP, SEXP xSEXP, SEXP d2mdxdbSEXP, SEXP wei_locsSEXP, SEXP wei_valsSEXP, SEXP probsSEXP, SEXP linkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vcov(vcovSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type d2mdxdb(d2mdxdbSEXP);
    Rcpp::traits::input_parameter< const arma::umat& >::type wei_locs(wei_locsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wei_vals(wei_valsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type link(linkSEXP);
    rcpp_result_gen = Rcpp::wrap(get_dydx_delta(beta, vcov, x, d2mdxdb, wei_locs, wei_vals, probs, link));
    return rcpp_result_gen;
END_RCPP
}
// count_nearest
arma::vec count_nearest(const arma::mat& vals, const arma::mat& grid, const arma::vec& weights);
RcppExport SEXP _DAME_count_nearest(SEXP valsSEXP, SEXP gridSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(count_nearest(vals, grid, weights));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DAME_get_ddx_mc", (DL_FUNC) &_DAME_get_ddx_mc, 9},
    {"_DAME_get_dydx_mc", (DL_FUNC) &_DAME_get_dydx_mc, 9},
    {"_DAME_get_ddx_delta", (DL_FUNC) &_DAME_get_ddx_delta, 8},
    {"_DAME_get_dydx_delta", (DL_FUNC) &_DAME_get_dydx_delta, 8},
    {"_DAME_count_nearest", (DL_FUNC) &_DAME_count_nearest, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_DAME(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
