# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_ddx_mc <- function(beta, vcov, x, xp, wei_locs, wei_vals, probs, link = 0L, iter = 1000L) {
    .Call(`_DAME_get_ddx_mc`, beta, vcov, x, xp, wei_locs, wei_vals, probs, link, iter)
}

get_dydx_mc <- function(beta, vcov, x, d2mdxdb, wei_locs, wei_vals, probs, link = 0L, iter = 1000L) {
    .Call(`_DAME_get_dydx_mc`, beta, vcov, x, d2mdxdb, wei_locs, wei_vals, probs, link, iter)
}

get_ddx_delta <- function(beta, vcov, x, xp, wei_locs, wei_vals, probs, link = 0L) {
    .Call(`_DAME_get_ddx_delta`, beta, vcov, x, xp, wei_locs, wei_vals, probs, link)
}

get_dydx_delta <- function(beta, vcov, x, d2mdxdb, wei_locs, wei_vals, probs, link = 0L) {
    .Call(`_DAME_get_dydx_delta`, beta, vcov, x, d2mdxdb, wei_locs, wei_vals, probs, link)
}

count_nearest <- function(vals, grid, weights) {
    .Call(`_DAME_count_nearest`, vals, grid, weights)
}

